# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2264031e46a0d2f3fc0a3858b0f4ccac7ffdcfa00151425c4e016fee2e4761c8c42e831561e62eb82becb42e8260c5dc165aeac28e106c6aedfec67ed797a113

test:
  secret_key_base: b522d077e85a2ceb48341e2a0a03fc8323b843bc987d11a0493104edb79c780421e9e13e740e6f98386c80a91ce5b7e62fdd435318767e051f6ff2b40a25b503

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
